---

- name: ingress | add trafeik chart repo to helm
  kubernetes.core.helm_repository:
    name: traefik
    repo_url: https://helm.traefik.io/traefik
  delegate_to: localhost
  become: false

- name: ingress | install traefik helm chart
  kubernetes.core.helm:
    name: traefik
    chart_ref: traefik/traefik
    release_namespace: traefik
    kubeconfig: "{{ k8s_admin_config_location }}"
    wait: true
    create_namespace: true
    values:
      deployment:
        kind: DaemonSet
      service:
        enabled: false
      securityContext:
        capabilities:
          drop: [ALL]
          add: [NET_BIND_SERVICE]
  delegate_to: localhost
  become: false

