---

#TODO: Check if multus/bridge cni are already installed
- name: main | deploy multus + bridge cni
  k8s:
    host: "https://{{ k8s_api_endpoint }}:6443"
    definition: "{{ lookup('url', item, split_lines=false) | from_yaml_all | list }}"
    kubeconfig: "{{ k8s_admin_config_location }}"
    validate:
      fail_on_error: true
  delegate_to: localhost
  become: false
  loop:
    - https://raw.githubusercontent.com/intel/multus-cni/master/images/multus-daemonset.yml
    - https://raw.githubusercontent.com/kubevirt/ovs-cni/master/examples/ovs-cni.yml


#TODO: check if kubevirt is installed before deploying
- name: main | deploy kubevirt
  k8s:
    host: "https://{{ k8s_api_endpoint }}:6443"
    definition: "{{ lookup('url', item, split_lines=false) | from_yaml_all | list }}"
    kubeconfig: "{{ k8s_admin_config_location }}"
    validate:
      fail_on_error: true
    wait: true
  delegate_to: localhost
  loop:
    - https://github.com/kubevirt/kubevirt/releases/download/{{ kubevirt_version }}/kubevirt-operator.yaml
    - https://github.com/kubevirt/kubevirt/releases/download/{{ kubevirt_version }}/kubevirt-cr.yaml
  become: false
