---

- name: linkerd | get linkerd cli
  get_url:
    url: https://github.com/linkerd/linkerd2/releases/download/edge-{{ k8s_linkerd_ver }}/linkerd2-cli-edge-{{ k8s_linkerd_ver }}-linux
    dest: /usr/bin/linkerd
    mode: 0755
    checksum: sha256:{{ lookup('url', 'https://github.com/linkerd/linkerd2/releases/download/edge-{{ k8s_linkerd_ver }}/linkerd2-cli-edge-{{ k8s_linkerd_ver }}-linux.sha256') }} 

- name: linkerd | check cluster
  command: linkerd check --pre
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  any_errors_fatal: true
  when: inventory_hostname == operation_master

- name: linkerd | install linkerd
  k8s:
    host: "https://{{ k8s_api_endpoint }}:6443"
    definition: "{{ lookup('pipe', 'linkerd install') | from_yaml_all | list }}"
    kubeconfig: "{{ k8s_admin_config_location }}"
  delegate_to: localhost
  become: false
  any_errors_fatal: true
  when: inventory_hostname == operation_master

- name: linkerd | check install
  command: linkerd check
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  any_errors_fatal: true
  when: inventory_hostname == operation_master