---

- name: main | include extra vars
  include_vars: "{{ item }}.yml"
  loop:
    - flannel

- name: main | disable swap if on
  command: swapoff -a
  when: ansible_swaptotal_mb != 0

- name: main | remove swap from fstab
  lineinfile:
    path: /etc/fstab
    regexp: swap
    state: absent

# tasks file for ansible-kubernetes
- name: main | prep sysctl for container runtime
  sysctl:
    name: "{{ item }}"
    sysctl_set: true
    value: "1"
    sysctl_file: /etc/sysctl.d/99-kubernetes-cri.conf
  loop:
    - net.bridge.bridge-nf-call-iptables
    - net.ipv4.ip_forward
    - net.bridge.bridge-nf-call-ip6tables

- name: main | copy k8s repo
  template:
    src: "{{ item }}"
    dest: /etc/yum.repos.d/
  loop:
    - docker-ce.repo
    - kubernetes.repo

- name: main | install base requirements
  yum:
    name:
      - kubelet
      - kubeadm
      - kubectl
      - docker-ce
      - kubernetes-cni
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
    enablerepo: kubernetes,docker-ce-stable

- name: main | copy docker daemon file
  copy:
    src: daemon.json
    dest: /etc/docker/

- name: main | start and enable docker
  service:
    name: docker
    state: started
    enabled: true

- name: main | run master configuration
  include_tasks: master.yml
  when: hostvars[inventory_hostname].k8s_master is defined

- name: main | run worker configuration
  include_tasks: worker.yml
  when: hostvars[inventory_hostname].k8s_master is not defined

- name: main | create json query fact
  set_fact:
    jq: "[*].metadata | [?contains(name,'flannel-ds')]"
  delegate_to: localhost
  delegate_facts: true
  when: inventory_hostname == operation_master

- name: worker | check if worker is online
  k8s_info:
    host: "https://{{ k8s_api_endpoint }}:6443"
    kubeconfig: "{{ k8s_admin_config_location }}"
    kind: Pod
    namespace: kube-system
    field_selectors:
      - status.phase=Running
  register: nodes
  until: nodes.resources | to_json | from_json | json_query(hostvars.localhost.jq) | length == ansible_play_hosts_all | length
  retries: 10
  delay: 10
  delegate_to: localhost
  become: false
  when: inventory_hostname == operation_master

- name: main | run linkerd install
  include_tasks: linkerd.yml
  when: hostvars[inventory_hostname].k8s_master is defined

- name: main | run nginx install
  include_tasks: nginx-ingress.yml
  when:
    - hostvars[inventory_hostname].k8s_master is defined
    - inventory_hostname == operation_master

- name: main | enable kubelet
  service:
    name: kubelet
    state: started
    enabled: true
