---

- name: master | open master ports
  firewalld:
    port: "{{ item }}"
    permanent: true
    state: enabled
  loop:
    - 6443/tcp
    - 2379-2380/tcp
    - 10250/tcp
    - 10251/tcp
    - 10252/tcp
    - 8285/udp
    - 8472/udp

- name: master | kubeadm init
  command: >
    kubeadm init --pod-network-cidr {{ k8s_pod_network_cidr }}
    --control-plane-endpoint {{ k8s_ctrl_plane_endpoint if k8s_ctrl_plane_endpoint is defined else ansible_default_ipv4.address }}
    --apiserver-advertise-address {{ k8s_api_endpoint if k8s_api_endpoint is defined else ansible_default_ipv4.address }}
  args:
    creates: /etc/kubernetes/pki/ca.key
  when: inventory_hostname == operation_master

- name: master | fetch admin kubeconfig
  fetch:
    src: /etc/kubernetes/admin.conf
    dest: "{{ k8s_admin_config_location }}"
    flat: true
  when: inventory_hostname == operation_master

- name: master | get join command
  shell: kubeadm token create --print-join-command
  register: node_join
  when: inventory_hostname == operation_master

- name: master | prune join command
  set_fact:
    node_join_cmd: "{{ node_join.stdout | trim }}"
  delegate_to: localhost
  delegate_facts: true

- name: master | deploy cluster networking/service mesh
  k8s:
    host: "https://{{ k8s_api_endpoint }}:6443"
    definition: "{{ lookup('url', 'https://raw.githubusercontent.com/coreos/flannel/2140ac876ef134e0ed5af15c65e414cf26827915/Documentation/kube-flannel.yml', split_lines=False ) | from_yaml_all  | list }}"
    kubeconfig: "{{ k8s_admin_config_location }}"
  when: inventory_hostname == operation_master
  delegate_to: localhost
  become: false
  any_errors_fatal: true

- include_tasks: linkerd.yml
