---

- name: nginx-ingress | clone repo
  git:
    repo: https://github.com/nginxinc/kubernetes-ingress/
    dest: /tmp/nginx-ingress
    version: "{{ k8s_nginx_ingress_ver }}"
  delegate_to: localhost


- name: nginx-ingress | deploy nginx ingress
  k8s:
    host: "https://{{ k8s_api_endpoint }}:6443"
    definition: "{{ lookup('file', '/tmp/nginx-ingress/deployments/'+item) | from_yaml_all | list }}"
    kubeconfig: "{{ k8s_admin_config_location }}"
    validate:
      fail_on_error: True
  delegate_to: localhost
  become: false
  any_errors_fatal: true
  loop:
    - common/ns-and-sa.yaml
    - rbac/rbac.yaml
    - common/custom-resource-definitions.yaml
    - daemon-set/nginx-ingress.yaml
    - service/nodeport.yaml
