---

- name: worker | open worker ports
  firewalld:
    port: "{{ item }}/tcp"
    permanent: true
    state: enabled
  loop:
    - 10250
    - 30000-32767

- name: worker | worker repo
  yum:
    name:
      - https://resources.ovirt.org/pub/yum-repo/ovirt-release{{ ovirt_release }}.rpm

- name: worker | configure networking
  include_tasks: worker-networking.yml

- name: worker | join worker to cluster
  # noqa 305
  shell: "{{ hostvars.localhost.node_join_cmd }}"
  args:
    creates:  /etc/kubernetes/pki/ca.crt