---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: master
    box: bento/centos-7
    interfaces:
        - network_name: private_network
          type: static
          ip: 192.168.200.2
    memory: 1024
  - name: worker-1
    interfaces:
        - network_name: private_network
          type: static
          ip: 192.168.200.3
    memory: 1024
    box: bento/centos-7
  - name: worker-2
    interfaces:
        - network_name: private_network
          type: static
          ip: 192.168.200.4
    memory: 1024
    box: bento/centos-7

provisioner:
  name: ansible
  inventory:
    host_vars:
      master:
        k8s_master: true
  lint:
    name: ansible-lint
verifier:
  name: testinfra
  lint:
    name: flake8
