---
- name: Prepare
  hosts: all
  become: true

  tasks:
    - name: install required packages
      yum:
        name:
          - epel-release
          - elrepo-release

    - name: update all packages
      yum:
        name: "*"
        state: latest

    - reboot:

    - name: set hostname
      hostname:
        name: "{{ inventory_hostname }}"

    - name: set /etc/hosts
      blockinfile:
        path: /etc/hosts
        block: |
          192.168.200.2 master 
          192.168.200.3 worker-1
          192.168.200.4 worker-2

    - name: update time quickly
      command: chronyc -a makestep
